services:
  app:
    build: .
    command: npm run dev
    ports:
      - 127.0.0.1:${API_PORT}:8000
      - 127.0.0.1:${VITE_PORT}:5173
    volumes:
      - .:/usr/src/app

  db:
    environment:
      MARIADB_DATABASE: laravel
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    image: mariadb
    ports:
      - 127.0.0.1:${MARIADB_PORT}:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: db
      UPLOAD_LIMIT: 128M
      PMA_USER: root
      PMA_PASSWORD: ""
    ports:
      - 127.0.0.1:${PHPMYADMIN_PORT}:80
