services:
  db:
    environment:
      MARIADB_DATABASE: laravel
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    image: mariadb
    ports:
      - ${MARIADB_PORT}:3306
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: db
      UPLOAD_LIMIT: 128M
      PMA_USER: root
      PMA_PASSWORD: ""
    ports:
      - ${PHPMYADMIN_PORT}:80

